ci:
  collect:
    url:
      - https://shop.dev.car.com/
      - https://shop.dev.car.com/honda
      - https://shop.dev.car.com/honda/civic

    numberOfRuns: 5

  #  assert:
  #    preset: 'lighthouse:recommended'
  #    assertions:
  #      uses-rel-preload: off
  #      uses-rel-preconnect: off

  upload:
    target: lhci
    serverBaseUrl: https://uc-kingcobra-lhciserver.azurewebsites.net/
    token: 6194aff9-214b-4e2f-a7b6-8b132a4b4559
